name: Image build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build-docker:
    name: cd/Build and push docker image
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'mattermost' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: cd/Login to Docker Hub
        uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139 # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: cd/Setup Docker Buildx
        uses: docker/setup-buildx-action@11e8a2e2910826a92412015c515187a2d6750279 # v2.4
      - name: cd/Docker build and push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{ github.ref_name }}
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker buildx build --push -t mattermost/pgbouncer-config-reload:${TAG} .
